spring.application.name=myspringbootlab
myprop.username=springboot
myprop.port=${random.int(1,100)}
# 로깅 설정 추가
logging.level.com.rookies5.myspringbootlab=debug
logging.pattern.console=%-5level %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n